# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Watchdiff < Formula
  desc "Watch a command and generate diffs from the output changes"
  homepage "https://github.com/luisdavim/watchdiff"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luisdavim/watchdiff/releases/download/v0.3.0/watchdiff_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e630661d9186c2dde734d2ed0b654e457216598862fa7c92301ebeefbe49e8eb"

      define_method(:install) do
        bin.install "watchdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luisdavim/watchdiff/releases/download/v0.3.0/watchdiff_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0786aaafd816e1dae610889431f8649e68180a23c130c5e360ddbf2a6aaded77"

      define_method(:install) do
        bin.install "watchdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luisdavim/watchdiff/releases/download/v0.3.0/watchdiff_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "7a319a002020e2f2bceb2f6bd1152c56994a605facfad72799860e53670f3524"
      define_method(:install) do
        bin.install "watchdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luisdavim/watchdiff/releases/download/v0.3.0/watchdiff_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8b7ec4b0a1f09d2c0c305d6cf8f669eed996bc931f4f0dae9447acaf2568421e"
      define_method(:install) do
        bin.install "watchdiff"
      end
    end
  end

  test do
    system "#{bin}/watchdiff", "-h"
  end
end
