# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Watchdiff < Formula
  desc "Watch a command and generate diffs from the output changes"
  homepage "https://github.com/luisdavim/watchdiff"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luisdavim/watchdiff/releases/download/v0.2.0/watchdiff_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6760359aa9b87ef33f288cfb502fbe7647314f581057c20de04f46bb5d858890"

      define_method(:install) do
        bin.install "watchdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luisdavim/watchdiff/releases/download/v0.2.0/watchdiff_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d52343f1cc309c3065c0fc13b93813009a09659ad5434343e652089505829f5b"

      define_method(:install) do
        bin.install "watchdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luisdavim/watchdiff/releases/download/v0.2.0/watchdiff_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b205520e4b9ef901988e2c309c597ee2f0530540942e04ec1c01290e5e90fc4a"
      define_method(:install) do
        bin.install "watchdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luisdavim/watchdiff/releases/download/v0.2.0/watchdiff_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "22a3dcf4a3d6d4e61e197647a304cd65a9767d2d7f56c18f8f0a7432879fa25d"
      define_method(:install) do
        bin.install "watchdiff"
      end
    end
  end

  test do
    system "#{bin}/watchdiff", "-h"
  end
end
