# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Watchdiff < Formula
  desc "Watch a command and generate diffs from the output changes"
  homepage "https://github.com/luisdavim/watchdiff"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luisdavim/watchdiff/releases/download/0.1.0/watchdiff_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "df5f17cce8ad76ef0ce8b036bb1d2f8073503927d8482705e96965ec405e6ff6"

      define_method(:install) do
        bin.install "watchdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luisdavim/watchdiff/releases/download/0.1.0/watchdiff_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "03d662a0bd1159df4aa271f27e3125db09ef1d659623cb5f882fb375d2aa270d"

      define_method(:install) do
        bin.install "watchdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luisdavim/watchdiff/releases/download/0.1.0/watchdiff_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "70689a2c83c56380aa8ba4c05960ad194931c1abff35fa9ddd216d00c0eb1ce4"
      define_method(:install) do
        bin.install "watchdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luisdavim/watchdiff/releases/download/0.1.0/watchdiff_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "61df370d67ae9b4f3cee515a55036da89e216dc77c03a1a6141e3c00a222d22b"
      define_method(:install) do
        bin.install "watchdiff"
      end
    end
  end

  test do
    system "#{bin}/watchdiff", "-h"
  end
end
